#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ExamsListAndroid.Resource", IsApplication=true)]

namespace ExamsListAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000e
			public const int buttonEnter = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int buttonFinal = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int examListView = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int finalResult = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int fragment_container = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int labelErrorLogin = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int logout = 2131099670;
			
			// aapt resource value: 0x7f060007
			public const int numberResultExam = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int option1 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int option2 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int pending = 2131099669;
			
			// aapt resource value: 0x7f06000a
			public const int prueba = 2131099658;
			
			// aapt resource value: 0x7f060017
			public const int refresh = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int resultExam = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int startButton = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int textDescription = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int textNQuestions = 2131099649;
			
			// aapt resource value: 0x7f060011
			public const int textNumber = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int textPassword = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int textQuestion = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int textResult = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int textTitle = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int textUser = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int titleExam = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ExamDetailsLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExamRowLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FinishExamLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LoginLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int QuestionLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040009
			public const int AllExams = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int ButtonFinalExam = 2130968596;
			
			// aapt resource value: 0x7f040008
			public const int Complete = 2130968584;
			
			// aapt resource value: 0x7f040011
			public const int ConnectionClose = 2130968593;
			
			// aapt resource value: 0x7f040004
			public const int Description = 2130968580;
			
			// aapt resource value: 0x7f04000e
			public const int Enter = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int ErrorLogin = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int FinalResult = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int Login = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int Logout = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int MessageLogOut = 2130968592;
			
			// aapt resource value: 0x7f040002
			public const int NQuestions = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int Number = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int Password = 2130968589;
			
			// aapt resource value: 0x7f040015
			public const int PendingUpload = 2130968597;
			
			// aapt resource value: 0x7f04000b
			public const int Refresh = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int Result = 2130968579;
			
			// aapt resource value: 0x7f040012
			public const int ResultExam = 2130968594;
			
			// aapt resource value: 0x7f040005
			public const int StartExam = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int User = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
